type Product = {
  id: number
  name: string
  description: string
  price: number
  image: string
  category: string
  badge: string
}
export function getProductsList(): Product[] {
  return [
    {
      id: 1,
      name: 'Produto 1',
      description: 'Esta é a descrição do produto 1',
      price: 9999999,
      image: 'https://generated.vusercontent.net/placeholder.svg',
      category: 'Categoria A',
      badge: 'Novo',
    },
    {
      id: 2,
      name: 'Produto 2',
      description: 'Esta é a descrição do produto 2',
      price: 999999,
      image: 'https://generated.vusercontent.net/placeholder.svg',
      category: 'Categoria B',
      badge: 'Promoção',
    },
    {
      id: 3,
      name: 'Produto 3',
      description: 'Esta é a descrição do produto 3',
      price: 99999,
      image: 'https://generated.vusercontent.net/placeholder.svg',
      category: 'Categoria A',
      badge: '',
    },
    {
      id: 4,
      name: 'Produto 4',
      description: 'Esta é a descrição do produto 4',
      price: 9999,
      image: 'https://generated.vusercontent.net/placeholder.svg',
      category: 'Categoria C',
      badge: '',
    },
    {
      id: 5,
      name: 'Produto 5',
      description: 'Esta é a descrição do produto 5',
      price: 999,
      image: 'https://generated.vusercontent.net/placeholder.svg',
      category: 'Categoria B',
      badge: '',
    },
    {
      id: 6,
      name: 'Produto 6',
      description: 'Esta é a descrição do produto 6',
      price: 99,
      image: 'https://generated.vusercontent.net/placeholder.svg',
      category: 'Categoria A',
      badge: '',
    },
    {
      id: 7,
      name: 'Produto 7',
      description: 'Esta é a descrição do produto 7',
      price: 9,
      image: 'https://generated.vusercontent.net/placeholder.svg',
      category: 'Categoria C',
      badge: '',
    },
    {
      id: 8,
      name: 'Produto 8',
      description: 'Esta é a descrição do produto 8',
      price: 10,
      image: 'https://generated.vusercontent.net/placeholder.svg',
      category: 'Categoria B',
      badge: '',
    },
    {
      id: 9,
      name: 'Produto 9',
      description: 'Esta é a descrição do produto 9',
      price: 10,
      image: 'https://generated.vusercontent.net/placeholder.svg',
      category: 'Categoria A',
      badge: '',
    },
    {
      id: 10,
      name: 'Produto 10',
      description: 'Esta é a descrição do produto 10',
      price: 10,
      image: 'https://generated.vusercontent.net/placeholder.svg',
      category: 'Categoria C',
      badge: '',
    },
    {
      id: 11,
      name: 'Produto 11',
      description: 'Esta é a descrição do produto 11',
      price: 10,
      image: 'https://generated.vusercontent.net/placeholder.svg',
      category: 'Categoria A',
      badge: '',
    },
    {
      id: 12,
      name: 'Produto 12',
      description: 'Esta é a descrição do produto 12',
      price: 10,
      image: 'https://generated.vusercontent.net/placeholder.svg',
      category: 'Categoria B',
      badge: '',
    },
    {
      id: 13,
      name: 'Produto 13',
      description: 'Esta é a descrição do produto 13',
      price: 10,
      image: 'https://generated.vusercontent.net/placeholder.svg',
      category: 'Categoria C',
      badge: '',
    },
    {
      id: 14,
      name: 'Produto 14',
      description: 'Esta é a descrição do produto 14',
      price: 10,
      image: 'https://generated.vusercontent.net/placeholder.svg',
      category: 'Categoria A',
      badge: '',
    },
    {
      id: 15,
      name: 'Produto 15',
      description: 'Esta é a descrição do produto 15',
      price: 10,
      image: 'https://generated.vusercontent.net/placeholder.svg',
      category: 'Categoria B',
      badge: '',
    },
    {
      id: 16,
      name: 'Produto 16',
      description: 'Esta é a descrição do produto 16',
      price: 10,
      image: 'https://generated.vusercontent.net/placeholder.svg',
      category: 'Categoria C',
      badge: '',
    },
    {
      id: 17,
      name: 'Produto 17',
      description: 'Esta é a descrição do produto 17',
      price: 10,
      image: 'https://generated.vusercontent.net/placeholder.svg',
      category: 'Categoria A',
      badge: '',
    },
    {
      id: 18,
      name: 'Produto 18',
      description: 'Esta é a descrição do produto 18',
      price: 10,
      image: 'https://generated.vusercontent.net/placeholder.svg',
      category: 'Categoria B',
      badge: '',
    },
    {
      id: 19,
      name: 'Produto 19',
      description: 'Esta é a descrição do produto 19',
      price: 10,
      image: 'https://generated.vusercontent.net/placeholder.svg',
      category: 'Categoria C',
      badge: '',
    },
    {
      id: 20,
      name: 'Produto 20',
      description: 'Esta é a descrição do produto 20',
      price: 10,
      image: 'https://generated.vusercontent.net/placeholder.svg',
      category: 'Categoria A',
      badge: '',
    },
  ]
}
